const ACTIONS = {
    GET_TOKEN: Symbol('GET_TOKEN'),
    GET_TOKEN_SUCCESS: Symbol('GET_TOKEN_SUCCESS'),
    GET_USER: Symbol('GET_USER'),
    GET_FEATURED_PLAYLISTS: Symbol('GET_FEATURED_PLAYLISTS'),
    FEATURED_PLAYLISTS_LOADED: Symbol('FEATURED_PLAYLISTS_LOADED'),
    SET_ALBUM: Symbol('SET_ALBUM'),
    GET_ALBUM_TRACKS: Symbol('GET_ALBUM_TRACKS'),
    GET_ALBUM_TRACKS_SUCCESS: Symbol('GET_ALBUM_TRACKS_SUCCESS'),
    UPDATE_BG: Symbol('UPDATE_BG')
};

export default ACTIONS;